### ISSUE TITLE
Roadmap as of 2019-01-25

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#1151]
The theme of this roadmap is to improve the usability of the desktop application, to make it more accessible for newcomers, and more usable for all.

# Roadmap

- [x] When in note list, move from one note to another using arrows
- [x] Delete note in list using DELETE key
- [x] When in list, press SPACE to toggle checkbox
- [x] In side bar, use arrow to go up and down
- [x] Use SPACE to expand/collapse a notebook
- [x] Side bar: Make Sync button fixed at the bottom
- [x] TAB: Side bar -> Note List -> Note title -> Note body
- [x] Local search: Press ENTER to go to next result
- [x] Local search: Press ESC to exit search
- [x] Config: Divide into section
- [x] Config: Make Save/Cancel sticky
- [x] Config: Select editor path with dialog
- [x] When selecting multiple notes: Display options that are currently in context menu, inside gray area where note normally is.
- [x] Global search: Add Help button next to input box
- [x] Remembered which note you had open, when you switched notebooks.
- [x] Save the cursor position when editing a note
- [x] Display note name when deleting note (for example, 20 first characters of the note title)
- [x] The shortcuts on macOS are a pain and some are missing
    - macOS: use `Shift+Command+F` to search in all notes (instead of F6)
    - macOS: use `Option-Command-S` to toggle sidebar (instead of F10)
    - `Command+k` for creating a link (see #1081)
    - New Notebook `Shift+Command+N`
- [x] Add help notebook
- [x] Improve Markdown rendering CSS in desktop and mobile app

# Help notebook

- Editing notes
    - Markdown
    - How to use external editor
- Attachment / Resources
- Sub-notebooks
- Searching
- Synchronisation
- End-to-end encryption (E2EE)
- Importing notes
- Exporting notes
- Notifications
- Donating and contributing

**Comment by ReekyMarko** [comment]
> Local search: Press ENTER to go to next result
Can we add ESC to exit search to this? It's what almost every single program out there uses.

**Comment by laurent22** [comment]
> Can we add ESC to exit search to this?

Yes that makes sense, I've added it to the list.

**Comment by tessus** [comment]
> Add help notebook

Would it make sense to allow hiding the help notebook? This option doesn't have to be specifically for this notebook. In certain cases it could make sense to hide notebooks. e.g. on a work computer you may want to hide a folder about cooking. Vice versa you might want to hide a project folder from work on your private machine.
The logic to implement this is not very complicated. It's more about how to handle nested folders. I'd also hide all subfolders, but others might have a different opinion. I guess this is the complicated part.

**Comment by sciurius** [comment]
@tessus I'd consider hiding all subfolders as most sensible.

**Comment by matsest** [comment]
I'm really liking these changes! Great UX improvements! Would you consider this issue for the current or next roadmap @laurent22?  

[FR] Move to Notebook in right-click menu (Desktop) #1094

**Comment by laurent22** [comment]
> > Add help notebook
> 
> Would it make sense to allow hiding the help notebook? This option doesn't have to be specifically for this notebook. In certain cases it could make sense to hide notebooks. e.g. on a work computer you may want to hide a folder about cooking. Vice versa you might want to hide a project folder from work on your private machine.
> The logic to implement this is not very complicated. It's more about how to handle nested folders. I'd also hide all subfolders, but others might have a different opinion. I guess this is the complicated part.

The main purpose of the Help notebook is so that the app doesn't start empty - it will already have a notebook and notes so that the user can see how it looks and works. Additionally it will provide some doc for new users. I assume current users will already know how it works and will learn new features as they go, but the Help notebook is mostly for new users, as a starting point.

So that's why I want to avoid any complex logic related to it. It will just be like any other notebook, it won't be updated and users can delete it if they wish. I think that'd be the simplest way to implement this without having to add new features just to support it.

**Comment by laurent22** [comment]
> I'm really liking these changes! Great UX improvements! Would you consider this issue for the current or next roadmap @laurent22?
> 
> [FR] Move to Notebook in right-click menu (Desktop) #1094

Not for the current one, but maybe in a future one.

**Comment by huyz** [comment]
> macOS: use I don't know which combo yet to toggle sidebar (instead of F10)

macOS Finder uses Option-Command-S to hide the sidebar.

**Comment by ewingrj** [comment]
evernote as well

**Comment by laurent22** [comment]
Let's go for Option-Command-S for the sidebar on macOS then.

**Comment by laurent22** [comment]
For the Help notebook, in the end I'm thinking about something simpler - just a "Welcome" notebook, which will present a summary of Joplin's features - something a bit similar to what Bear is doing:

- **Welcome to Joplin** - Introduces the app and explains the main parts of the user interface (sidebar, note list, etc.)
- **Organising and writing notes** - Explain how to create notebook, how to write notes, and some basic info about Markdown (with links to the complete doc). How to use an external editor. How to attach images and files.
- **Synchronising your notes** - Basic help on how to setup synchronisation and E2EE.
- **Importing and exporting notes** - How to get the notes from Evernote (since new users often are migrating from it), from other programs, and how to export the notes.
- **Tips** (not sure how to say in English, basically like in French "Trucs & astuces") - More general info about the rest of Joplin - search, keyboard shortcuts, config screen, web clipper, etc. Then links to contribute, forum, donations, etc.

If you notice something that might be missing or could be different, feel free to post about it here.

**Comment by laurent22** [comment]
Well, doing the Welcome notes made me realise how ugly looking the note CSS is at the moment. I put it together quickly when I wrote the app and never looked back, so there's a lot of things wrong with margins, colours and so on, there's even `a { color: blue }` :-) (I probably thought I'd lookup a proper colour later but never did). So I've added improving the CSS as an item in this roadmap.

**Comment by CalebJohn** [comment]
@laurent22 It's a coincidence, I was thinking the same thing and started working on a pull request yesterday, but you beat me to it :). I've made a pull request to include the styling I had made for tables and blockquote #1185 I understand that you may be working on the same thing (and prefer your version). So no worries if you don't merge that one.

**Comment by laurent22** [comment]
@CalebJohn, I didn't change the quote and table styling so we can use your changes too actually.

**Comment by tessus** [comment]
@laurent22 since you have changed the look and feel in this roadmap, maybe you could also use a monospace font for editing notes on mobile. If you don't want to do this as the default, maybe a config option on mobile could be added.

**Comment by laurent22** [comment]
@tessus, that wouldn't be for this release since it's mostly about the desktop (trying to keep things focused). The reason it's not monospace at the moment is that it takes more space than regular font, so it can be an issue on small mobile screens. If we change the default we need to do some tests to see how it looks, what font size we can use, etc.

**Comment by tessus** [comment]
@laurent22 thx for the info

**Comment by subi54** [comment]
Rather than do monospace font, it would be better to have custom CSS. Somewhere in options, type/copy your CSS.

It removes your headache as a developer in the long run because you can't cater to individual needs and say where @tessus needs his body {font-family: mono}, some other person might like something from Google fonts and request that.

Before all that though mobile app needs a better scrolling experience in editing window.

**Comment by tessus** [comment]
@subi54 this is not a bad idea - I like it. unfortunately there's no custom CSS in the mobile apps - at least not yet.

**Comment by laurent22** [comment]
For info, I've also added the macOS shortcuts, except the one for new notebook because it's already taken to focus the note title. Although creating a new notebook is probably not a very common operation so using the mouse is acceptable.

**Comment by tessus** [comment]
@laurent22 Thanks, Laurent. I would have created the PR for the shortcuts, but as you know my mind is currently somewhere else.

> Although creating a new notebook is probably not a very common operation so using the mouse is acceptable.

Yep, this makes sense.

**Comment by shscs911** [comment]
@laurent22, Can you please add a Keyboard Shortcut for Sync (e.g. `Ctrl+S`) ? It'd be really helpful.

**Comment by laurent22** [comment]
> @laurent22, Can you please add a Keyboard Shortcut for Sync (e.g. `Ctrl+S`) in Windows ? It'd be really helpful.

I'm wondering why this would be needed? After you make a change, it auto-sync 30 seconds later so I would have thought that's sufficiently fast?

**Comment by shscs911** [comment]
> I'm wondering why this would be needed? After you make a change, it auto-sync 30 seconds later so I would have thought that's sufficiently fast?

@laurent22  Yeah, that would be the case normally, but I've faced many situations where I had to write something quickly before the laptop battery dies and waiting for auto-sync is not ideal. Besides, auto-saving in the middle of writing something causes conflicts. This is even more troublesome when the internet connection is spotty (as is often the case for me). The optimum solution would be to add an option to disable auto-sync completely(even light sync of last write) and use only manual sync. I know my situation is a bit of an edge-case, but it'd be much appreciated, if you could implement it. Thank you for listening to my rant.

**Comment by huyz** [comment]
If the delay were 5 seconds, no shortcut wouldn’t be needed. But 30 seconds is a long time to wait for sync to happen before u can close your laptop to sleep.

**Comment by laurent22** [comment]
@shscs911, for now you can simply click on the Synchronise button and it will do it right away. That button has also been made sticky in this release so that will make this easier too. I wouldn't be opposed to Ctrl/Cmd+S to force a sync, if someone wants to make a PR.

Disabling sync altogether on the other hand is not an option. The problem is that frequent syncs are needed to prevent conflicts. If someone disables sync and forgets about it, they'll end up with many conflicts that are annoying to fix, and often they'll think it's the app that's buggy. So basically because of all this, sync will almost always be automated and will happen as quickly as possible.

**Comment by laurent22** [comment]
This release for this roadmap will be available soon, so the issue can now be closed.

**Comment by tessus** [comment]
> I wouldn't be opposed to Ctrl/Cmd+S to force a sync, if someone wants to make a PR.

I can have a look at it in a few days. Please let me know, if I should also add a menu item or just add a shortcut.

**Comment by laurent22** [comment]
> I can have a look at it in a few days. Please let me know, if I should also add a menu item or just add a shortcut.

That would be great, and yes with a menu item. For now, let's put all functionalities that have a shortcut in the menu as it serves as a documentation for the shortcuts too.
