### ISSUE TITLE
WYSIWYG to-do list

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#2710]
This post is to keep track of what's left to do for the WYSIWYG editor. Related to #176

- [ ] Add back support for external editing
- [ ] Allow creating code blocks for Katex, Mermaid, Fountain, and for actual source code.
- [ ] Allow creating checkboxes
- [ ] Improve handling of non-standard Markdown plugins
- [ ] Add "Insert date time" button
- [ ] Add Tag button
- [ ] Display tags below title
- [ ] Add "Alarm" button
- [ ] Add "Note Properties" button
- [ ] Check that when clicking "Back" from note history, it goes back to WYSIWYG editor
- [ ] Add "Content Properties" button
