### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#3723]
This is to give an idea of the coming versions. The roadmap may change over time and feature might be added or removed from certain planned versions.

All platforms share a good part of the code so they will also share the same major and minor version numbers, although some releases might be desktop or mobile only depending on the features.

# Version 1.6

- [x] Add support for Joplin Server as a sync target
- [x] Make it easier to compile content scripts in plugins - https://github.com/laurent22/joplin/issues/4229

# Version 1.5

- [x] Try to notarize macOS application
- [x] Review linkify handler and don't linkify links that don't start with http/https/file

# Version 1.4

- [x] All: Standardise Markdown flavour - https://github.com/laurent22/joplin/issues/3839
- [x] Desktop: Spell checking for Rich Text editor - https://github.com/laurent22/joplin/issues/275
- [x] Desktop: Upgrade to Electron 10.x
- [x] Split repo into multiple packages? possibly using Lerna https://github.com/lerna/lerna
- [x] Plugins: Add namespace to command names and deprecate old command names by making them aliases to new command names.
- [x] Plugins: Add UI to install a plugin, list them and enabled/disable a plugin
- [x] Plugins: Review requested features and see what can be added

# Version 1.3

- [x] Desktop: Plugin system (#3257)
- [x] Desktop: Remove export to JSON feature (See [here](https://github.com/laurent22/joplin/issues/3723#issuecomment-689603686) for rationale)
- [x] Fix sidebar resize issue https://discourse.joplinapp.org/t/pre-release-1-2-is-available-for-testing/11207/33?u=laurent

# Version 1.2

- [x] Desktop: Cancelling sync doesn't work anymore
- [x] Desktop: UI update (#3586)
- [x] Desktop: Fix missed highlighting when using the global search (#3717)
- [x] Disable fuzzy search
- [x] Fix search result highlights in mobile app
- [x] Make search bar wider - https://discourse.joplinapp.org/t/1-2-2-search-field/11216/6?u=laurent
- [x] Update tag background colour? https://discourse.joplinapp.org/t/pre-release-1-2-is-available-for-testing/11207/4?u=laurent
- [x] Implement UI tweaks - https://discourse.joplinapp.org/t/pre-release-1-2-is-available-for-testing/11207/19?u=laurent

# Version 1.1

- [x] Search engine fuzzy search (#3713)
- [x] Mobile: Disable beta editor on Android for now (it crashes the app)
- [x] Desktop: Keyboard shortcut editor
- [x] Desktop: Changed from Ace Editor to CodeMirror
- [x] Desktop: App should do full sync on startup immediately
- [x] Mobile: Investigate slow down on sync startup

# Version 1.0

- [x] Check if temp folder is created on sync target on new profile

**Comment by Gamegenorator** [comment]
What is the reasoning for removing the ability to export to JSON?

**Comment by laurent22** [comment]
> What is the reasoning for removing the ability to export to JSON?

The feature is incomplete because it's possible to export as JSON but not import back, and this might be confusing. But also we already have a computer-friendly format when exporting as RAW, and maintaining two such formats doesn't make sense. If someone needs the notes as JSON, it's trivial to parse the RAW format and create JSON from it.

**Comment by MxD-js** [comment]
Can an built in update system be added in the near future?. I do appreciate all the updates, but it seems like every week, if not more often than this, I open my laptop and a new update is out, I loving the pace the development is going but each time I need to download a new version of Jopin file, download it, open it and update it, then have to search where I saved the new update and delete the installer. I would like to see an update system that Google has going on with their Chrome browser. Silent updates in the background and Chrome is always updated. 

Or at the very least, clean after the install. Excellent work done thus far.

**Comment by laurent22** [comment]
There’s no plan for it, but I’ll disable auto-updates by default in future versions, so it’d be up to the users if they want to update.

**Comment by ehamminga** [comment]
Hi Laurent, Joplin seems to be on version 2.1 by now. Would it be possible to see an updated roadmap?
